spring:
  datasource:
    url: jdbc:h2:mem:starbux
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
order:
  discount:
    percent: 25
    min-value: 12
    min-count: 3